### ISSUE TITLE
Issue with Deploy.sh

### ISSUE THREAD

**Issue by Baker** [decent-im/decent.im#14]
So I run deploy.sh in ubuntu 14.0 LTS x64 

I get this : https://gyazo.com/f46b68ade60c2b185f327c49d56b0a0b 

Then I run apt-get install pwgen and re-run sh deploy.sh

and get: 
https://gyazo.com/216ae87cd172b37534338423bb7a6108

**Comment by andrey-utkin** [comment]
Hello and welcome!

So sorry - I've omitted pwgen from list of dependencies. If you want, you may author a pull request :)

Regarding "source" failure. It is assumed that you run deploy.sh which resides in a full workcopy of this git repo, so it sources "./secret/env.sh" if you have, and if not, then it falls back to "./secret_env.sh.sample" which is supplied in this git repo. So the latter should definitely be available.

Very glad to see people who are interested in using this.
Please note that this git repo is slightly out of sync with production node lately, due to lack of my spare time. But I am going to maintain it.
Also please note that currently the deployment script assumes pristine VPS. So it's best to test new changes on non-production node to decrease downtime.
As soon as we have users community, we may support different deployment model :)

**Comment by Baker** [comment]
Ok, so I renamed the /secret_env.sh.sample to /secret_env.sh same with env, is that wrong? should i leave it named by default ?

**Comment by andrey-utkin** [comment]
You are supposed to have either `./secret/env.sh` or `./secret_env.sh.sample`. `/secret_env.sh` or `secret_env.sh` are not looked at.

**Comment by Baker** [comment]
I will adjust, that do you mind I make some installation docs, and do you need any help with this project? Would love to assist :)

**Comment by andrey-utkin** [comment]
Any help would be lovely.
Also feel free to review the overall model of operation and suggest changes.
Some refinement is also needed in regard to how user configures the stuff. Lately I decided that user should provide something like /etc/jabber/, but this may need more thought.

Also I've heard of Sovereighn project which has "idempotent updates". However I believe sane updates by standard package manager should be enough, but not everything is nicely packaged (at last for decent.im). So I consider doing some packaging work for Ubuntu, or even transitioning to Gentoo to have easier updates from git/hg of upstream.

**Comment by Baker** [comment]
Yeah we should connect and talk I have some idea, and would love to be apart of it :)

**Comment by andrey-utkin** [comment]
Would be happy to talk. mailto:andrey_utkin@fastmail.com, xmpp:andrey.utkin@decent.im
